"""update user/category model

Revision ID: 48fcf5b2c1da
Revises: 24cfaf0254ef
Create Date: 2026-07-08 14:37:43.499797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fcf5b2c1da'
down_revision: Union[str, Sequence[str], None] = '24cfaf0254ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
