"""add_rating_and_cleanup

Revision ID: 7489c9d88d9e
Revises: b5ff74b7ac50
Create Date: 2026-07-09 11:02:24.687679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7489c9d88d9e'
down_revision: Union[str, Sequence[str], None] = 'b5ff74b7ac50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.execute("DELETE FROM categories")
    op.execute("DELETE FROM users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
