"""update user/category model

Revision ID: dae973422de0
Revises: 48fcf5b2c1da
Create Date: 2026-07-08 15:04:17.859996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae973422de0'
down_revision: Union[str, Sequence[str], None] = '48fcf5b2c1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.execute("DELETE FROM categories")
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
