name: fastapi-ecommerce-prod

services:
  web:
    build:
      # Указываем контекст сборки - текущую директорию проекта
      context: .
      # Используем Dockerfile.prod из директории app
      dockerfile: ./app/Dockerfile.prod
    # Запускаем ASGI-приложение через сервер приложений Gunicorn с воркерами Uvicorn
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Запускаем контейнер после старта контейнера базы данных
    depends_on:
      - db

  db:
    # Используем официальный образ PostgreSQL версии 16
    image: postgres:16
    # Монтируем том postgres_data в /var/lib/postgresql/data контейнера для хранения данных БД
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Задаём переменные окружения для инициализации БД и пользователя
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    # Собираем образ nginx из локальной директории nginx
    build: nginx
    # Монтируем том media_data в /var/www/media контейнера для доступа к медиафайлам
    volumes:
      - media_data:/var/www/media
    # Открываем порт 80 внутри и снаружи
    ports:
      - 80:80
    # Запускаем контейнер после старта контейнера web-приложения
    depends_on:
      - web
volumes:
  # Определяем том для хранения данных БД
  postgres_data:
  media_data: